export const UPDATE_TEZOS = "UPDATE_TEZOS";
export const SET_CONTRACTS = "SET_CONTRACTS";
export const GET_ROUND_STATUS = "GET_ROUND_STATUS";
export const GET_WALLET_DATA = "GET_WALLET_DATA";
export const GET_ROUNDS_DATA = "GET_ROUNDS_DATA";
export const GET_NEW_ROUND_PROPOSALS_DATA = "GET_NEW_ROUND_PROPOSALS_DATA";
export const GET_DISPUTES_DATA = "GET_DISPUTES_DATA";
